# Before you start :
   - These exercises are related to the Subsetting and Descriptive Stats lessons.
   - Keep in mind that you need to use some of the functions you learned in the previous lessons.
   - All datasets are provided in the `your-code` folder of this lab.
   - Elaborate your codes and outputs as much as you can.
   - Try your best to answer the questions and complete the tasks and most importantly enjoy the process!!!

#### Import all the libraries that are necessary

In [1]:
import pandas as pd

# Challenge 1

#### In this challenge we will use the `Temp_States.csv` file. 

#### First import it into a data frame called `temp`.

In [2]:
temp = pd.read_csv('D:\gurdit singh\lab-descriptive-stats-en\your-code\Temp_States.csv')

#### Print `temp`

In [3]:
print(temp)

         City        State  Temperature
0         NYC     New York    19.444444
1      Albany     New York     9.444444
2     Buffalo     New York     3.333333
3    Hartford  Connecticut    17.222222
4  Bridgeport  Connecticut    14.444444
5      Treton   New Jersey    22.222222
6      Newark   New Jersey    20.000000

#### Explore the data types of the Temp dataframe. What type of data do we have? Comment your result.

In [8]:
temp.dtypes  # City and State are objects (strings), Temp is float64
ny_data = temp[temp['State'] == 'New York']
print(ny_data.head())
print(ny_data.shape)  # See if you got any rows

      City     State  Temperature
0      NYC  New York    19.444444
1   Albany  New York     9.444444
2  Buffalo  New York     3.333333
(3, 3)

#### Select the rows where state is New York

In [13]:
my_rows = temp[temp['State'] == 'New York']
print(my_rows)

      City     State  Temperature
0      NYC  New York    19.444444
1   Albany  New York     9.444444
2  Buffalo  New York     3.333333

#### What is the average of the temperature of cities in New York?

In [14]:
my_avg = temp[temp['State'] == 'New York']['Temperature'].mean()
print(my_avg)

10.74074074074074

#### We want to know cities and states with Temperature above 15 degress Celcius

In [15]:
high_temp = temp[temp['Temperature'] > 15][['City', 'State', 'Temperature']]
print(high_temp)

       City        State  Temperature
0       NYC     New York    19.444444
3  Hartford  Connecticut    17.222222
5    Treton   New Jersey    22.222222
6    Newark   New Jersey    20.000000

#### Now, return only the cities that have a temperature above 15 degress Celcius

In [16]:
high_temp_cities = temp[temp['Temperature'] > 15]['City'].tolist()
print(high_temp_cities)

['NYC', 'Hartford', 'Treton', 'Newark']

#### We want to know which cities have a temperature above 15 degrees Celcius and below 20 degrees Celcius

*Hint: First write the condition then select the rows.*

In [17]:
condition = (temp['Temperature'] > 15) & (temp['Temperature'] < 20)
mid_temp_rows = temp[condition][['City', 'State', 'Temperature']]
print(mid_temp_rows)

       City        State  Temperature
0       NYC     New York    19.444444
3  Hartford  Connecticut    17.222222

In [18]:
temp['State'].value_counts()

State
New York       3
Connecticut    2
New Jersey     2
Name: count, dtype: int64

#### Find the mean and the standard deviation of the temperature of each state.

*Hint: Use functions from Data Manipulation lesson*

In [19]:
state_stats = temp.groupby('State')['Temperature'].agg(['mean', 'std']).round(2)
print(state_stats)

              mean   std
State
Connecticut  15.83  1.96
New Jersey   21.11  1.57
New York     10.74  8.13

# Challenge 2

#### Load the `employee.csv` file into a DataFrame. Call the dataframe `employee`

In [20]:
temp = pd.read_csv('D:\gurdit singh\lab-descriptive-stats-en\your-code\Employee.csv')

#### Explore the data types of the Temp dataframe. Comment your results

In [21]:
temp = pd.read_csv('D:\gurdit singh\lab-descriptive-stats-en\your-code\Temp_States.csv')
state_stats = temp.groupby('State')['Temperature'].agg(['mean', 'std']).round(2)
print(state_stats)

              mean   std
State
Connecticut  15.83  1.96
New Jersey   21.11  1.57
New York     10.74  8.13

In [22]:
print(temp.dtypes)

City            object
State           object
Temperature    float64
dtype: object

#### Show visually the frequency distribution (histogram) of the employee dataset. In few words describe these histograms?

In [23]:
import pandas as pd
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [24]:
employee = pd.read_csv('D:\gurdit singh\lab-descriptive-stats-en\your-code\Employee.csv')
fig = make_subplots(rows=1, cols=2, subplot_titles=('Years', 'Salary'))
fig.add_trace(go.Histogram(x=employee['Years'], opacity=0.7, nbinsx=9), row=1, col=1)
fig.add_trace(go.Histogram(x=employee['Salary'], opacity=0.7, nbinsx=10), row=1, col=2)
fig.update_layout(title='Employee Dataset Frequency Distributions', xaxis_title='Years', yaxis_title='Frequency',
                  xaxis2_title='Salary ($)', yaxis2_title='Frequency')
fig.show()

#### What's the average salary in this company?

In [25]:
avg_salary = employee['Salary'].mean()
print(round(avg_salary, 2))

48.89

#### What's the highest salary?

In [26]:
max_salary = employee['Salary'].max()
print(max_salary)

70

#### What's the lowest salary?

In [27]:
low_salary = employee['Salary'].min()
print(low_salary)

30

#### Who are the employees with the lowest salary?

In [28]:
min_salary = employee['Salary'].min()
low_salary_emps = employee[employee['Salary'] == min_salary][['Name', 'Salary']]
print(low_salary_emps)

    Name  Salary
1  Maria      30
2  David      30

#### Could you give all the information about an employee called David?

In [29]:
david_info = employee[employee['Name'] == 'David']
print(david_info)

    Name Department Education Gender    Title  Years  Salary
2  David         HR    Master      M  analyst      2      30

#### Could you give only David's salary?

In [30]:
david_salary = employee[employee['Name'] == 'David']['Salary']
print(david_salary.iloc[0])

30

#### Print all the rows where job title is associate

In [31]:
associates = employee[employee['Title'] == 'associate']
print(associates)

     Name Department Education Gender      Title  Years  Salary
4  Samuel      Sales    Master      M  associate      3      55
5     Eva      Sales  Bachelor      F  associate      2      55
7   Pedro         IT       Phd      M  associate      7      60

#### Print the first 3 rows of your dataframe

##### Tip : There are 2 ways to do it. Do it both ways

In [32]:
employee.head(3)

    Name Department Education Gender    Title  Years  Salary
0   Jose         IT  Bachelor      M  analyst      1      35
1  Maria         IT    Master      F  analyst      2      30
2  David         HR    Master      M  analyst      2      30

In [33]:
employee.iloc[:3]

    Name Department Education Gender    Title  Years  Salary
0   Jose         IT  Bachelor      M  analyst      1      35
1  Maria         IT    Master      F  analyst      2      30
2  David         HR    Master      M  analyst      2      30

#### Find the employees who's title is associate and the salary above 55?

In [34]:
high_paid_associates = employee[(employee['Title'] == 'associate') & (employee['Salary'] > 55)]
print(high_paid_associates)

    Name Department Education Gender      Title  Years  Salary
7  Pedro         IT       Phd      M  associate      7      60

#### Group the employees based on their number of years of employment. What are the average salaries in each group?

In [35]:
years_salary_avg = employee.groupby('Years')['Salary'].mean().round(2)
print(years_salary_avg)

Years
1    35.00
2    38.33
3    55.00
4    35.00
7    60.00
8    70.00
Name: Salary, dtype: float64

####  What is the average Salary per title?

In [36]:
title_salary_avg = employee.groupby('Title')['Salary'].mean().round(2)
print(title_salary_avg)

Title
VP           70.00
analyst      32.50
associate    56.67
Name: Salary, dtype: float64

#### Show a visual summary of the data using boxplot. What Are the First and Third Quartiles? Comment your results.

* Hint : Quantiles vs Quartiles*
In Probability and Statistics, quantiles are cut points dividing the range of a probability distribution into continuous intervals with equal probabilities. When division is into four parts the values of the variate corresponding to 25%, 50% and 75% of the total distribution are called quartiles.

In [39]:
import pandas as pd
import plotly.express as px
fig = px.box(employee, y='Salary', title='Salary Distribution Boxplot')
fig.update_layout(yaxis_title='Salary ($)')
fig.show()

In [40]:
q1 = employee['Salary'].quantile(0.25)
print(q1)

35.0

In [41]:
q3 = employee['Salary'].quantile(0.75)
print(q3)

60.0

#### Is the mean salary per gender different?

In [42]:
print(employee.groupby('Gender')['Salary'].mean().round(2))

Gender
F    47.5
M    50.0
Name: Salary, dtype: float64

#### Find the minimum, mean and the maximum of all numeric columns for each Department.

##### Hint: Use functions from Data Manipulation lesson

In [43]:
dept_stats = employee.groupby('Department')[['Years', 'Salary']].agg(['min', 'mean', 'max']).round(2)
print(dept_stats)

           Years           Salary
             min  mean max    min   mean max
Department
HR             2  4.67   8     30  45.00  70
IT             1  4.50   8     30  48.75  70
Sales          2  2.50   3     55  55.00  55

### Bonus Question

#### For each department, compute the difference between the maximal salary and the minimal salary.

##### * Hint: try using `agg` or `apply` and `lambda`*

In [44]:
dept_range = employee.groupby('Department')['Salary'].agg(lambda x: x.max() - x.min())
print(dept_range)

Department
HR       40
IT       40
Sales     0
Name: Salary, dtype: int64

# Challenge 3

#### Open the Orders.csv dataset. Name your dataset orders

In [ ]:
# your answer here

#### Explore your dataset by looking at the data types and the summary statistics. Comment your results

In [ ]:
# your answer here

In [ ]:
# your answer here

####  What is the average Purchase Price?

In [ ]:
# your answer here

#### What were the highest and lowest purchase prices?

In [ ]:
# your answer here

In [ ]:
# your answer here

#### Select all the customers we have in Spain

In [45]:
# your answer here

#### How many customers do we have in Spain?
##### Hint : Use value_counts()

In [ ]:
# your answer here

#### Select all the customers who have bought more than 50 items ?

In [ ]:
# your answer here

#### Select orders from Spain that are above 50 items

In [ ]:
# your answer here

#### Select all free orders

In [ ]:
# your answer here

#### Select all orders that are 'lunch bag'
#### Hint: Use string functions

In [ ]:
# your answer here

#### Select all orders that are made in 2011 and are 'lunch bag'

In [ ]:
# your answer here

#### Show the frequency distribution of the amount spent in Spain.

In [ ]:
# your answer here

#### Select all orders made in the month of August

In [ ]:
# your answer here

#### Select how many orders are made by countries in the month of August
##### Hint: Use value_counts()

In [ ]:
# your answer here

#### What's the  average amount of money spent by country

In [ ]:
# your answer here

#### What's the most expensive item?

In [ ]:
# your answer here

#### What was the average amount spent per year ?

In [ ]:
# your answer here